# Generated by Django 5.1.4 on 2024-12-29 23:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Me',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('city', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=10)),
                ('date_birth', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('degree', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Unavaliable', 'Unavaliable')], max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
