# Generated by Django 5.1.4 on 2024-12-30 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='me',
            name='body',
            field=models.TextField(default=''),
        ),
    ]
