# Generated by Django 5.1.4 on 2024-12-30 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_me_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='me',
            name='image',
            field=models.ImageField(default='default', upload_to='media'),
        ),
    ]
