# Generated by Django 5.1.4 on 2024-12-30 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='user_image',
            field=models.ImageField(default='default', upload_to='media'),
        ),
    ]
