# Generated by Django 5.1.4 on 2024-12-30 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_test_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='user_image',
            field=models.ImageField(blank=True, default='default', null=True, upload_to='media'),
        ),
    ]
